version: '2'
services:
  l4lb:
    build:
      context: ./l4lb
    image: l4lb:latest
    container_name: l4lb
    ports:
      - "6565:6565"
    depends_on: 
      - grpc1
      - grpc2
  l7lb:
    build:
      context: ./l7lb
    image: l7lb:latest
    container_name: l7lb
    ports:
      - "6564:80"
    depends_on: 
      - grpc1
      - grpc2
  grpc1:
    build: ./grpcserver
    image: grpcserver:latest
    container_name: grpc1
    environment:
      - "GRPC_PORT=6566"
      - "SERVER_PORT=8081"
      - "EUREKA_HOST=grpceureka"
    ports:
      - "8081:8081"
  grpc2:
    build: ./grpcserver
    image: grpcserver:latest
    container_name: grpc2
    environment:
      - "GRPC_PORT=6567"
      - "SERVER_PORT=8082"
      - "EUREKA_HOST=grpceureka"
    ports:
      - "8082:8082"
  grpceureka:
    build: ./grpceureka
    image: grpceureka:latest
    container_name: grpceureka
    ports:
      - "8761:8761"
  grpcfront:
    build: ./grpcfront
    image: grpcfront:latest
    container_name: grpcfront
    ports:
      - "8080:8080"
    environment:
      - "EUREKA_HOST=grpceureka"
    depends_on: 
      - grpceureka
      - grpc1
      - grpc2
    