// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fizbuz.proto

package my.rpc;

public interface FizBuzListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.rpc.FizBuzList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string answer = 1;</code>
   */
  java.util.List<java.lang.String>
      getAnswerList();
  /**
   * <code>repeated string answer = 1;</code>
   */
  int getAnswerCount();
  /**
   * <code>repeated string answer = 1;</code>
   */
  java.lang.String getAnswer(int index);
  /**
   * <code>repeated string answer = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnswerBytes(int index);
}
