// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fizbuz.proto

package my.rpc;

public interface FizBuzAnswerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.rpc.FizBuzAnswer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string answer = 1;</code>
   */
  java.lang.String getAnswer();
  /**
   * <code>string answer = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnswerBytes();
}
