// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fizbuz.proto

package my.rpc;

public interface FromToOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.rpc.FromTo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 from = 1;</code>
   */
  int getFrom();

  /**
   * <code>int32 to = 2;</code>
   */
  int getTo();
}
