// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my/rpc/fizbuz.proto

package my.rpc;

public final class Fizbuz {
  private Fizbuz() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_rpc_InputNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_rpc_InputNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_rpc_FromTo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_rpc_FromTo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_rpc_FizBuzAnswer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_rpc_FizBuzAnswer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_my_rpc_FizBuzList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_my_rpc_FizBuzList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023my/rpc/fizbuz.proto\022\006my.rpc\032\034google/ap" +
      "i/annotations.proto\032\031validator/validator" +
      ".proto\"&\n\013InputNumber\022\027\n\003num\030\001 \001(\005B\n\202\265\030\002" +
      "\020d\212\265\030\000\"\"\n\006FromTo\022\014\n\004from\030\001 \001(\005\022\n\n\002to\030\002 \001" +
      "(\005\"\036\n\014FizBuzAnswer\022\016\n\006answer\030\001 \001(\t\"\034\n\nFi" +
      "zBuzList\022\016\n\006answer\030\001 \003(\t2\222\002\n\rFizBuzServi" +
      "ce\022M\n\tFizBuzOne\022\023.my.rpc.InputNumber\032\024.m" +
      "y.rpc.FizBuzAnswer\"\025\202\323\344\223\002\017\022\r/fizbuz/{num" +
      "}\0227\n\013FizBuzRange\022\016.my.rpc.FromTo\032\024.my.rp" +
      "c.FizBuzAnswer\"\0000\001\022:\n\013FizBuzBatch\022\023.my.r" +
      "pc.InputNumber\032\022.my.rpc.FizBuzList\"\000(\001\022=" +
      "\n\nFizBuzMany\022\023.my.rpc.InputNumber\032\024.my.r" +
      "pc.FizBuzAnswer\"\000(\0010\001B\n\n\006my.rpcP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          validator.Validator.getDescriptor(),
        }, assigner);
    internal_static_my_rpc_InputNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_my_rpc_InputNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_rpc_InputNumber_descriptor,
        new java.lang.String[] { "Num", });
    internal_static_my_rpc_FromTo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_my_rpc_FromTo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_rpc_FromTo_descriptor,
        new java.lang.String[] { "From", "To", });
    internal_static_my_rpc_FizBuzAnswer_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_my_rpc_FizBuzAnswer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_rpc_FizBuzAnswer_descriptor,
        new java.lang.String[] { "Answer", });
    internal_static_my_rpc_FizBuzList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_my_rpc_FizBuzList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_my_rpc_FizBuzList_descriptor,
        new java.lang.String[] { "Answer", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(validator.Validator.range);
    registry.add(validator.Validator.required);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    validator.Validator.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
