// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fizbuz.proto

package my.rpc;

public interface InputNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:my.rpc.InputNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num = 1;</code>
   */
  int getNum();
}
