// Code generated by protoc-gen-go. DO NOT EDIT.
// source: validator/validator.proto

package validator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Required struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Required) Reset()         { *m = Required{} }
func (m *Required) String() string { return proto.CompactTextString(m) }
func (*Required) ProtoMessage()    {}
func (*Required) Descriptor() ([]byte, []int) {
	return fileDescriptor_e972accd7c1f0747, []int{0}
}

func (m *Required) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Required.Unmarshal(m, b)
}
func (m *Required) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Required.Marshal(b, m, deterministic)
}
func (m *Required) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Required.Merge(m, src)
}
func (m *Required) XXX_Size() int {
	return xxx_messageInfo_Required.Size(m)
}
func (m *Required) XXX_DiscardUnknown() {
	xxx_messageInfo_Required.DiscardUnknown(m)
}

var xxx_messageInfo_Required proto.InternalMessageInfo

type Range struct {
	Min                  int32    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_e972accd7c1f0747, []int{1}
}

func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (m *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(m, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Range) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

var E_Range = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Range)(nil),
	Field:         50000,
	Name:          "validator.range",
	Tag:           "bytes,50000,opt,name=range",
	Filename:      "validator/validator.proto",
}

var E_Required = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Required)(nil),
	Field:         50001,
	Name:          "validator.required",
	Tag:           "bytes,50001,opt,name=required",
	Filename:      "validator/validator.proto",
}

func init() {
	proto.RegisterType((*Required)(nil), "validator.Required")
	proto.RegisterType((*Range)(nil), "validator.Range")
	proto.RegisterExtension(E_Range)
	proto.RegisterExtension(E_Required)
}

func init() { proto.RegisterFile("validator/validator.proto", fileDescriptor_e972accd7c1f0747) }

var fileDescriptor_e972accd7c1f0747 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4b, 0xcc, 0xc9,
	0x4c, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0xe1, 0x02, 0x52, 0x0a, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x89, 0xa4, 0xd2, 0x34,
	0xfd, 0x94, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x02, 0xb8, 0x62, 0x25, 0x2e, 0x2e, 0x8e, 0xa0, 0xd4,
	0xc2, 0xd2, 0xcc, 0xa2, 0xd4, 0x14, 0x25, 0x6d, 0x2e, 0xd6, 0xa0, 0xc4, 0xbc, 0xf4, 0x54, 0x21,
	0x01, 0x2e, 0xe6, 0xdc, 0xcc, 0x3c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x10, 0x13, 0x2c,
	0x92, 0x58, 0x21, 0xc1, 0x04, 0x15, 0x49, 0xac, 0xb0, 0x72, 0xe7, 0x62, 0x2d, 0x02, 0x2b, 0x96,
	0xd5, 0x83, 0x58, 0xa2, 0x07, 0xb3, 0x44, 0xcf, 0x2d, 0x33, 0x35, 0x27, 0xc5, 0xbf, 0xa0, 0x24,
	0x33, 0x3f, 0xaf, 0x58, 0xe2, 0x42, 0x1b, 0xb3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x80, 0x1e, 0xc2,
	0x9d, 0x60, 0x5b, 0x82, 0x20, 0xfa, 0xad, 0x02, 0xb8, 0x38, 0x8a, 0xa0, 0x2e, 0x20, 0x64, 0xd6,
	0x45, 0xa8, 0x59, 0xc2, 0xc8, 0x66, 0x41, 0xf5, 0x06, 0xc1, 0x4d, 0x49, 0x62, 0x03, 0xeb, 0x36,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x34, 0x7f, 0xcf, 0x24, 0x01, 0x00, 0x00,
}
