// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fizbuz.proto

package my.rpc;

/**
 * Protobuf type {@code my.rpc.FizBuzList}
 */
public  final class FizBuzList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:my.rpc.FizBuzList)
    FizBuzListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FizBuzList.newBuilder() to construct.
  private FizBuzList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FizBuzList() {
    answer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FizBuzList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              answer_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            answer_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        answer_ = answer_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return my.rpc.Fizbuz.internal_static_my_rpc_FizBuzList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return my.rpc.Fizbuz.internal_static_my_rpc_FizBuzList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            my.rpc.FizBuzList.class, my.rpc.FizBuzList.Builder.class);
  }

  public static final int ANSWER_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList answer_;
  /**
   * <code>repeated string answer = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAnswerList() {
    return answer_;
  }
  /**
   * <code>repeated string answer = 1;</code>
   */
  public int getAnswerCount() {
    return answer_.size();
  }
  /**
   * <code>repeated string answer = 1;</code>
   */
  public String getAnswer(int index) {
    return answer_.get(index);
  }
  /**
   * <code>repeated string answer = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAnswerBytes(int index) {
    return answer_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < answer_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, answer_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < answer_.size(); i++) {
        dataSize += computeStringSizeNoTag(answer_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAnswerList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof my.rpc.FizBuzList)) {
      return super.equals(obj);
    }
    my.rpc.FizBuzList other = (my.rpc.FizBuzList) obj;

    boolean result = true;
    result = result && getAnswerList()
        .equals(other.getAnswerList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAnswerCount() > 0) {
      hash = (37 * hash) + ANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getAnswerList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static my.rpc.FizBuzList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static my.rpc.FizBuzList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static my.rpc.FizBuzList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static my.rpc.FizBuzList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static my.rpc.FizBuzList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static my.rpc.FizBuzList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static my.rpc.FizBuzList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static my.rpc.FizBuzList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static my.rpc.FizBuzList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static my.rpc.FizBuzList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static my.rpc.FizBuzList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static my.rpc.FizBuzList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(my.rpc.FizBuzList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code my.rpc.FizBuzList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:my.rpc.FizBuzList)
      my.rpc.FizBuzListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return my.rpc.Fizbuz.internal_static_my_rpc_FizBuzList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return my.rpc.Fizbuz.internal_static_my_rpc_FizBuzList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              my.rpc.FizBuzList.class, my.rpc.FizBuzList.Builder.class);
    }

    // Construct using my.rpc.FizBuzList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      answer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return my.rpc.Fizbuz.internal_static_my_rpc_FizBuzList_descriptor;
    }

    @Override
    public my.rpc.FizBuzList getDefaultInstanceForType() {
      return getDefaultInstance();
    }

    @Override
    public my.rpc.FizBuzList build() {
      my.rpc.FizBuzList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public my.rpc.FizBuzList buildPartial() {
      my.rpc.FizBuzList result = new my.rpc.FizBuzList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        answer_ = answer_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.answer_ = answer_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof my.rpc.FizBuzList) {
        return mergeFrom((my.rpc.FizBuzList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(my.rpc.FizBuzList other) {
      if (other == getDefaultInstance()) return this;
      if (!other.answer_.isEmpty()) {
        if (answer_.isEmpty()) {
          answer_ = other.answer_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAnswerIsMutable();
          answer_.addAll(other.answer_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      my.rpc.FizBuzList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (my.rpc.FizBuzList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList answer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAnswerIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        answer_ = new com.google.protobuf.LazyStringArrayList(answer_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAnswerList() {
      return answer_.getUnmodifiableView();
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public int getAnswerCount() {
      return answer_.size();
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public String getAnswer(int index) {
      return answer_.get(index);
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAnswerBytes(int index) {
      return answer_.getByteString(index);
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public Builder setAnswer(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAnswerIsMutable();
      answer_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public Builder addAnswer(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAnswerIsMutable();
      answer_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public Builder addAllAnswer(
        Iterable<String> values) {
      ensureAnswerIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, answer_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public Builder clearAnswer() {
      answer_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string answer = 1;</code>
     */
    public Builder addAnswerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAnswerIsMutable();
      answer_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:my.rpc.FizBuzList)
  }

  // @@protoc_insertion_point(class_scope:my.rpc.FizBuzList)
  private static final my.rpc.FizBuzList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new my.rpc.FizBuzList();
  }

  public static my.rpc.FizBuzList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FizBuzList>
      PARSER = new com.google.protobuf.AbstractParser<FizBuzList>() {
    @Override
    public FizBuzList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FizBuzList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FizBuzList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FizBuzList> getParserForType() {
    return PARSER;
  }

  @Override
  public my.rpc.FizBuzList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

